export const data = JSON.parse("{\"key\":\"v-57134882\",\"path\":\"/posts/%E6%80%A7%E8%83%BD%E4%BC%98%E5%8C%96/%E6%80%A7%E8%83%BD%E4%BC%98%E5%8C%96.html\",\"title\":\"性能优化\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"性能优化 性能优化的目的 首屏时间 首屏可交互时间 首次有意义内容渲染时间 性能检测： https://developers.google.com/speed/pagespeed/insights polyfill: https://polyfill.io/v3/url-builder\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/posts/%E6%80%A7%E8%83%BD%E4%BC%98%E5%8C%96/%E6%80%A7%E8%83%BD%E4%BC%98%E5%8C%96.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"饮东的博客\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"性能优化\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"性能优化 性能优化的目的 首屏时间 首屏可交互时间 首次有意义内容渲染时间 性能检测： https://developers.google.com/speed/pagespeed/insights polyfill: https://polyfill.io/v3/url-builder\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"性能优化\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"性能优化的目的\",\"slug\":\"性能优化的目的\",\"link\":\"#性能优化的目的\",\"children\":[]},{\"level\":2,\"title\":\"优化方法\",\"slug\":\"优化方法\",\"link\":\"#优化方法\",\"children\":[{\"level\":3,\"title\":\"只请求当前需要的资源\",\"slug\":\"只请求当前需要的资源\",\"link\":\"#只请求当前需要的资源\",\"children\":[]},{\"level\":3,\"title\":\"缩减资源体积\",\"slug\":\"缩减资源体积\",\"link\":\"#缩减资源体积\",\"children\":[]},{\"level\":3,\"title\":\"时序优化\",\"slug\":\"时序优化\",\"link\":\"#时序优化\",\"children\":[]},{\"level\":3,\"title\":\"合理的利用缓存\",\"slug\":\"合理的利用缓存\",\"link\":\"#合理的利用缓存\",\"children\":[]}]},{\"level\":2,\"title\":\"如果一段js执行时间非常长，怎么去分析\",\"slug\":\"如果一段js执行时间非常长-怎么去分析\",\"link\":\"#如果一段js执行时间非常长-怎么去分析\",\"children\":[{\"level\":3,\"title\":\"阿里云oss支持通过链接后面品参数来做图片的格式转换，尝试写一下，把任意图片格式转换为webp，需要注意什么\",\"slug\":\"阿里云oss支持通过链接后面品参数来做图片的格式转换-尝试写一下-把任意图片格式转换为webp-需要注意什么\",\"link\":\"#阿里云oss支持通过链接后面品参数来做图片的格式转换-尝试写一下-把任意图片格式转换为webp-需要注意什么\",\"children\":[]},{\"level\":3,\"title\":\"如果有巨量的图片需要展示，除了懒加载的方式，还有没有其他方法限制一下同时加载的图片数量\",\"slug\":\"如果有巨量的图片需要展示-除了懒加载的方式-还有没有其他方法限制一下同时加载的图片数量\",\"link\":\"#如果有巨量的图片需要展示-除了懒加载的方式-还有没有其他方法限制一下同时加载的图片数量\",\"children\":[]}]}],\"readingTime\":{\"minutes\":4.07,\"words\":1222},\"filePathRelative\":\"posts/性能优化/性能优化.md\",\"excerpt\":\"<h1> 性能优化</h1>\\n<h2> 性能优化的目的</h2>\\n<ol>\\n<li>首屏时间</li>\\n<li>首屏可交互时间</li>\\n<li>首次有意义内容渲染时间</li>\\n</ol>\\n<p>性能检测： <a href=\\\"https://developers.google.com/speed/pagespeed/insights\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">https://developers.google.com/speed/pagespeed/insights</a></p>\\n<p>polyfill: <a href=\\\"https://polyfill.io/v3/url-builder\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">https://polyfill.io/v3/url-builder</a></p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
