export const data = JSON.parse("{\"key\":\"v-ca97ba32\",\"path\":\"/zh/posts/%E5%89%8D%E7%AB%AF%E5%B7%A5%E7%A8%8B%E5%8C%96/Vite%E7%9F%A5%E8%AF%86%E8%B0%83%E7%A0%94.html\",\"title\":\"\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"Vite知识调研 Vite和WebPack的区别，各有哪些优点和不足 Vite打包为什么可以那么“快” 将现有的项目迁移使用Vite存在哪些问题 Vite生产环境为什么选择Rollup做构建工具 ESbuild和babel-plugin-import相关知识 Vite同期竞品比较 1.Vite和Webpack的区别，各有哪些优点和不足\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/zh/posts/%E5%89%8D%E7%AB%AF%E5%B7%A5%E7%A8%8B%E5%8C%96/Vite%E7%9F%A5%E8%AF%86%E8%B0%83%E7%A0%94.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"饮东的博客\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Vite知识调研 Vite和WebPack的区别，各有哪些优点和不足 Vite打包为什么可以那么“快” 将现有的项目迁移使用Vite存在哪些问题 Vite生产环境为什么选择Rollup做构建工具 ESbuild和babel-plugin-import相关知识 Vite同期竞品比较 1.Vite和Webpack的区别，各有哪些优点和不足\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Vite知识调研\",\"slug\":\"vite知识调研\",\"link\":\"#vite知识调研\",\"children\":[{\"level\":3,\"title\":\"1.Vite和Webpack的区别，各有哪些优点和不足\",\"slug\":\"_1-vite和webpack的区别-各有哪些优点和不足\",\"link\":\"#_1-vite和webpack的区别-各有哪些优点和不足\",\"children\":[]},{\"level\":3,\"title\":\"2. Vite打包为什么可以那么“快”\",\"slug\":\"_2-vite打包为什么可以那么-快\",\"link\":\"#_2-vite打包为什么可以那么-快\",\"children\":[]},{\"level\":3,\"title\":\"3.将现有的项目迁移使用Vite存在哪些问题\",\"slug\":\"_3-将现有的项目迁移使用vite存在哪些问题\",\"link\":\"#_3-将现有的项目迁移使用vite存在哪些问题\",\"children\":[]},{\"level\":3,\"title\":\"4.Vite生产环境为什么选择Rollup做构建工具\",\"slug\":\"_4-vite生产环境为什么选择rollup做构建工具\",\"link\":\"#_4-vite生产环境为什么选择rollup做构建工具\",\"children\":[]},{\"level\":3,\"title\":\"5.. ESbuild和babel-plugin-import\",\"slug\":\"_5-esbuild和babel-plugin-import\",\"link\":\"#_5-esbuild和babel-plugin-import\",\"children\":[]},{\"level\":3,\"title\":\"6.Vite同期竞品比较\",\"slug\":\"_6-vite同期竞品比较\",\"link\":\"#_6-vite同期竞品比较\",\"children\":[]}]},{\"level\":2,\"title\":\"总结\",\"slug\":\"总结\",\"link\":\"#总结\",\"children\":[]}],\"readingTime\":{\"minutes\":14.59,\"words\":4376},\"filePathRelative\":\"zh/posts/前端工程化/Vite知识调研.md\",\"excerpt\":\"<h2> Vite知识调研</h2>\\n<ol>\\n<li>\\n<p>Vite和WebPack的区别，各有哪些优点和不足</p>\\n</li>\\n<li>\\n<p>Vite打包为什么可以那么“快”</p>\\n</li>\\n<li>\\n<p>将现有的项目迁移使用Vite存在哪些问题</p>\\n</li>\\n<li>\\n<p>Vite生产环境为什么选择Rollup做构建工具</p>\\n</li>\\n<li>\\n<p>ESbuild和babel-plugin-import相关知识</p>\\n</li>\\n<li>\\n<p>Vite同期竞品比较</p>\\n</li>\\n</ol>\\n<hr>\\n<h3> 1.Vite和Webpack的区别，各有哪些优点和不足</h3>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
