export const data = JSON.parse("{\"key\":\"v-f45610ae\",\"path\":\"/zh/posts/JavaScipt%E5%9F%BA%E7%A1%80/JavaScript%E6%96%B9%E6%B3%95/%E6%9F%A5%E7%BC%BA%E8%A1%A5%E6%BC%8F.html\",\"title\":\"查缺补漏\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"查缺补漏 跨域 Jsonp 在\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/zh/posts/JavaScipt%E5%9F%BA%E7%A1%80/JavaScript%E6%96%B9%E6%B3%95/%E6%9F%A5%E7%BC%BA%E8%A1%A5%E6%BC%8F.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"饮东的博客\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"查缺补漏\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"查缺补漏 跨域 Jsonp 在\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"查缺补漏\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"跨域\",\"slug\":\"跨域\",\"link\":\"#跨域\",\"children\":[]},{\"level\":2,\"title\":\"css权重\",\"slug\":\"css权重\",\"link\":\"#css权重\",\"children\":[]},{\"level\":2,\"title\":\"css +~\",\"slug\":\"css\",\"link\":\"#css\",\"children\":[]},{\"level\":2,\"title\":\"伪类和伪元素的区别\",\"slug\":\"伪类和伪元素的区别\",\"link\":\"#伪类和伪元素的区别\",\"children\":[]},{\"level\":2,\"title\":\"长宽比2:1\",\"slug\":\"长宽比2-1\",\"link\":\"#长宽比2-1\",\"children\":[]},{\"level\":2,\"title\":\"禁止复制粘贴\",\"slug\":\"禁止复制粘贴\",\"link\":\"#禁止复制粘贴\",\"children\":[]},{\"level\":2,\"title\":\"取消请求\",\"slug\":\"取消请求\",\"link\":\"#取消请求\",\"children\":[]},{\"level\":2,\"title\":\"cjs/esm\",\"slug\":\"cjs-esm\",\"link\":\"#cjs-esm\",\"children\":[]},{\"level\":2,\"title\":\"Package.json\",\"slug\":\"package-json\",\"link\":\"#package-json\",\"children\":[]},{\"level\":2,\"title\":\"webpack\",\"slug\":\"webpack\",\"link\":\"#webpack\",\"children\":[]},{\"level\":2,\"title\":\"js 压缩代码\",\"slug\":\"js-压缩代码\",\"link\":\"#js-压缩代码\",\"children\":[]},{\"level\":2,\"title\":\"tree shaking\",\"slug\":\"tree-shaking\",\"link\":\"#tree-shaking\",\"children\":[]},{\"level\":2,\"title\":\"http状态码\",\"slug\":\"http状态码\",\"link\":\"#http状态码\",\"children\":[]},{\"level\":2,\"title\":\"Http2\",\"slug\":\"http2\",\"link\":\"#http2\",\"children\":[]},{\"level\":2,\"title\":\"vue3\",\"slug\":\"vue3\",\"link\":\"#vue3\",\"children\":[]},{\"level\":2,\"title\":\"Es6 Proxy\",\"slug\":\"es6-proxy\",\"link\":\"#es6-proxy\",\"children\":[]}],\"readingTime\":{\"minutes\":5.62,\"words\":1687},\"filePathRelative\":\"zh/posts/JavaScipt基础/JavaScript方法/查缺补漏.md\",\"excerpt\":\"<h1> 查缺补漏</h1>\\n<h2> 跨域</h2>\\n<ul>\\n<li>\\n<p><strong>Jsonp</strong> 在</p></li></ul>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
