export const data = JSON.parse("{\"key\":\"v-925b3b1a\",\"path\":\"/posts/%E6%B5%8F%E8%A7%88%E5%99%A8%E7%9B%B8%E5%85%B3%E7%9F%A5%E8%AF%86/Event%20Loop%E5%9C%A8%E6%B5%8F%E8%A7%88%E5%99%A8%E4%B8%AD%E5%92%8CNode%E7%8E%AF%E5%A2%83%E4%B8%AD%E7%9A%84%E5%8C%BA%E5%88%AB.html\",\"title\":\"Event Loop在浏览器中和Node环境中的区别\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"Event Loop在浏览器中和Node环境中的区别 浏览器中的Event Loop 事件循环中的异步队列有两种：macro（宏任务）队列和 micro（微任务）队列。宏任务队列可以有多个，微任务队列只有一个。 常见的 macro-task 比如：setTimeout、setInterval、 setImmediate、script（整体代码）、 I/O 操作、UI 渲染等。 常见的 micro-task 比如: process.nextTick、new Promise().then(回调)、MutationObserver(html5 新特性) 等。\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/posts/%E6%B5%8F%E8%A7%88%E5%99%A8%E7%9B%B8%E5%85%B3%E7%9F%A5%E8%AF%86/Event%20Loop%E5%9C%A8%E6%B5%8F%E8%A7%88%E5%99%A8%E4%B8%AD%E5%92%8CNode%E7%8E%AF%E5%A2%83%E4%B8%AD%E7%9A%84%E5%8C%BA%E5%88%AB.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"饮东的博客\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Event Loop在浏览器中和Node环境中的区别\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Event Loop在浏览器中和Node环境中的区别 浏览器中的Event Loop 事件循环中的异步队列有两种：macro（宏任务）队列和 micro（微任务）队列。宏任务队列可以有多个，微任务队列只有一个。 常见的 macro-task 比如：setTimeout、setInterval、 setImmediate、script（整体代码）、 I/O 操作、UI 渲染等。 常见的 micro-task 比如: process.nextTick、new Promise().then(回调)、MutationObserver(html5 新特性) 等。\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Event Loop在浏览器中和Node环境中的区别\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"浏览器中的Event Loop\",\"slug\":\"浏览器中的event-loop\",\"link\":\"#浏览器中的event-loop\",\"children\":[]},{\"level\":2,\"title\":\"Node环境中的Event Loop\",\"slug\":\"node环境中的event-loop\",\"link\":\"#node环境中的event-loop\",\"children\":[]}],\"readingTime\":{\"minutes\":2.32,\"words\":696},\"filePathRelative\":\"posts/浏览器相关知识/Event Loop在浏览器中和Node环境中的区别.md\",\"excerpt\":\"<h1> Event Loop在浏览器中和Node环境中的区别</h1>\\n<h2> 浏览器中的Event Loop</h2>\\n<p>事件循环中的异步队列有两种：macro（宏任务）队列和 micro（微任务）队列。宏任务队列可以有多个，微任务队列只有一个。\\n常见的 macro-task 比如：setTimeout、setInterval、 setImmediate、script（整体代码）、 I/O 操作、UI 渲染等。\\n常见的 micro-task 比如: process.nextTick、new Promise().then(回调)、MutationObserver(html5 新特性) 等。</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
