export const data = JSON.parse("{\"key\":\"v-5ec61931\",\"path\":\"/posts/JavaScipt%E5%9F%BA%E7%A1%80/%E7%BA%A2%E5%AE%9D%E4%B9%A6/13.2%E7%94%A8%E6%88%B7%E4%BB%A3%E7%90%86%E6%A3%80%E6%B5%8B.html\",\"title\":\"13.2用户代理检测\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"13.2用户代理检测 概念 在http1.0和1.1的协议中，要求浏览器应该向服务器发送一段包含浏览器名称和版本信息的字符串 通过浏览器携带的用户代理字符串来判断当前是什么浏览器的方法叫做用户代理检测 早期的使用 美国国家超级计算机中心发布于1993年的Mosaic是早期web浏览器的代表。它的用户代理字符串格式是： Mosaic/0.9 后面崛起的网景公司开发浏览器时，将 浏览器代号取为 Mozilla （Mosaic Killer） 最开始它的字符串格式是这样的Mozilla/Version [language] (Platform; Encryption) 除了http要求的信息，它还额外携带了当前语言、操作系统和加密类型\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/posts/JavaScipt%E5%9F%BA%E7%A1%80/%E7%BA%A2%E5%AE%9D%E4%B9%A6/13.2%E7%94%A8%E6%88%B7%E4%BB%A3%E7%90%86%E6%A3%80%E6%B5%8B.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"饮东的博客\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"13.2用户代理检测\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"13.2用户代理检测 概念 在http1.0和1.1的协议中，要求浏览器应该向服务器发送一段包含浏览器名称和版本信息的字符串 通过浏览器携带的用户代理字符串来判断当前是什么浏览器的方法叫做用户代理检测 早期的使用 美国国家超级计算机中心发布于1993年的Mosaic是早期web浏览器的代表。它的用户代理字符串格式是： Mosaic/0.9 后面崛起的网景公司开发浏览器时，将 浏览器代号取为 Mozilla （Mosaic Killer） 最开始它的字符串格式是这样的Mozilla/Version [language] (Platform; Encryption) 除了http要求的信息，它还额外携带了当前语言、操作系统和加密类型\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"13.2用户代理检测\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"概念\",\"slug\":\"概念\",\"link\":\"#概念\",\"children\":[]},{\"level\":2,\"title\":\"早期的使用\",\"slug\":\"早期的使用\",\"link\":\"#早期的使用\",\"children\":[]},{\"level\":2,\"title\":\"发展的规律\",\"slug\":\"发展的规律\",\"link\":\"#发展的规律\",\"children\":[]},{\"level\":2,\"title\":\"现在的用户代理字符串\",\"slug\":\"现在的用户代理字符串\",\"link\":\"#现在的用户代理字符串\",\"children\":[]},{\"level\":2,\"title\":\"没伪造的特例\",\"slug\":\"没伪造的特例\",\"link\":\"#没伪造的特例\",\"children\":[]},{\"level\":2,\"title\":\"如何正确判断浏览器\",\"slug\":\"如何正确判断浏览器\",\"link\":\"#如何正确判断浏览器\",\"children\":[]},{\"level\":2,\"title\":\"如何使用\",\"slug\":\"如何使用\",\"link\":\"#如何使用\",\"children\":[]}],\"readingTime\":{\"minutes\":3.9,\"words\":1169},\"filePathRelative\":\"posts/JavaScipt基础/红宝书/13.2用户代理检测.md\",\"excerpt\":\"<h1> 13.2用户代理检测</h1>\\n<h2> 概念</h2>\\n<p>在http1.0和1.1的协议中，要求浏览器应该向服务器发送一段包含<strong>浏览器名称</strong>和<strong>版本信息</strong>的字符串\\n通过浏览器携带的<strong>用户代理字符串</strong>来判断当前是什么浏览器的方法叫做<strong>用户代理检测</strong></p>\\n<h2> 早期的使用</h2>\\n<p>美国国家超级计算机中心发布于1993年的<code>Mosaic</code>是早期web浏览器的代表。它的用户代理字符串格式是： <code>Mosaic/0.9</code>\\n后面崛起的网景公司开发浏览器时，将 浏览器代号取为 <code>Mozilla</code>  （Mosaic Killer）\\n最开始它的字符串格式是这样的<code>Mozilla/Version [language] (Platform; Encryption)</code>\\n除了http要求的信息，它还额外携带了当前语言、操作系统和加密类型</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
