export const data = JSON.parse("{\"key\":\"v-d2452084\",\"path\":\"/posts/JavaScipt%E5%9F%BA%E7%A1%80/%E7%BA%A2%E5%AE%9D%E4%B9%A6/14.1%20%E8%8A%82%E7%82%B9%E5%B1%82%E7%BA%A7%20Node%E8%8A%82%E7%82%B9.html\",\"title\":\"第十四章DOM  14.1节点层级 Node节点\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"第十四章DOM 14.1节点层级 Node节点 由于对BOM整章的学习，现在在心态上已经完全可以去学习DOM了。今天只看完了14.1.1小节，不过也算有所收获，毕竟每晚的时间有限，重在积累。 DOM概念 DOM表示由多层节点构成的文档，通过它开发者可以添加、删除和修改页面的各个部分。 document节点表示每个文档的根节点。 Node类型 DOM Level1中就描述了node的接口，这个接口是面向所有DOM节点的，都必须实现。 每个节点都存在一个叫做 nodeType的属性，表示节点的类型。它由定义好的十二个数值分别表示不同的节点，也就是规范规定的映射。\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/posts/JavaScipt%E5%9F%BA%E7%A1%80/%E7%BA%A2%E5%AE%9D%E4%B9%A6/14.1%20%E8%8A%82%E7%82%B9%E5%B1%82%E7%BA%A7%20Node%E8%8A%82%E7%82%B9.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"饮东的博客\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"第十四章DOM  14.1节点层级 Node节点\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"第十四章DOM 14.1节点层级 Node节点 由于对BOM整章的学习，现在在心态上已经完全可以去学习DOM了。今天只看完了14.1.1小节，不过也算有所收获，毕竟每晚的时间有限，重在积累。 DOM概念 DOM表示由多层节点构成的文档，通过它开发者可以添加、删除和修改页面的各个部分。 document节点表示每个文档的根节点。 Node类型 DOM Level1中就描述了node的接口，这个接口是面向所有DOM节点的，都必须实现。 每个节点都存在一个叫做 nodeType的属性，表示节点的类型。它由定义好的十二个数值分别表示不同的节点，也就是规范规定的映射。\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"第十四章DOM  14.1节点层级 Node节点\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"DOM概念\",\"slug\":\"dom概念\",\"link\":\"#dom概念\",\"children\":[]},{\"level\":2,\"title\":\"Node类型\",\"slug\":\"node类型\",\"link\":\"#node类型\",\"children\":[{\"level\":3,\"title\":\"nodeName和nodeValue\",\"slug\":\"nodename和nodevalue\",\"link\":\"#nodename和nodevalue\",\"children\":[]},{\"level\":3,\"title\":\"节点关系\",\"slug\":\"节点关系\",\"link\":\"#节点关系\",\"children\":[]},{\"level\":3,\"title\":\"操纵节点\",\"slug\":\"操纵节点\",\"link\":\"#操纵节点\",\"children\":[]}]}],\"readingTime\":{\"minutes\":4.43,\"words\":1330},\"filePathRelative\":\"posts/JavaScipt基础/红宝书/14.1 节点层级 Node节点.md\",\"excerpt\":\"<h1> 第十四章DOM  14.1节点层级 Node节点</h1>\\n<p>由于对BOM整章的学习，现在在心态上已经完全可以去学习DOM了。今天只看完了14.1.1小节，不过也算有所收获，毕竟每晚的时间有限，重在积累。</p>\\n<h2> DOM概念</h2>\\n<p>DOM表示由多层节点构成的文档，通过它开发者可以添加、删除和修改页面的各个部分。</p>\\n<p>document节点表示每个文档的根节点。</p>\\n<h2> Node类型</h2>\\n<p>DOM Level1中就描述了node的接口，这个接口是面向所有DOM节点的，都必须实现。</p>\\n<p>每个节点都存在一个叫做 <strong>nodeType</strong>的属性，表示节点的类型。它由定义好的十二个数值分别表示不同的节点，也就是规范规定的映射。</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
