export const data = JSON.parse("{\"key\":\"v-234fa010\",\"path\":\"/posts/JavaScipt%E5%9F%BA%E7%A1%80/%E7%BA%A2%E5%AE%9D%E4%B9%A6/%E7%AC%AC%E5%8D%81%E5%9B%9B%E7%AB%A0%2014.1.5-14.1.9(%E7%BB%AD%E6%8E%A5%E5%89%8D%E9%9D%A2%E6%9C%AC%E7%AB%A0%E5%AE%8C%EF%BC%89.html\",\"title\":\"第十四章 14.1.5-14.1.9(续接前面本章完)\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"第十四章 14.1.5-14.1.9(续接前面本章完) 14.1.5 Comment 类型 注释类型节点，一般不主动创建。和文本类型一样继承自 CharacterData 基类，除了 splitText() 之外拥有其他所有 Text节点的方法。 注释的实际内容可以通过 nodeValue 或 data 获得 document.createComment() 可以创建注释节点 1.4.1.6 CDATASection 类型 XML 中特有的 CDATA 区块 可以用 createCDataSection() 创建并传入节点内容创建\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/posts/JavaScipt%E5%9F%BA%E7%A1%80/%E7%BA%A2%E5%AE%9D%E4%B9%A6/%E7%AC%AC%E5%8D%81%E5%9B%9B%E7%AB%A0%2014.1.5-14.1.9(%E7%BB%AD%E6%8E%A5%E5%89%8D%E9%9D%A2%E6%9C%AC%E7%AB%A0%E5%AE%8C%EF%BC%89.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"饮东的博客\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"第十四章 14.1.5-14.1.9(续接前面本章完)\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"第十四章 14.1.5-14.1.9(续接前面本章完) 14.1.5 Comment 类型 注释类型节点，一般不主动创建。和文本类型一样继承自 CharacterData 基类，除了 splitText() 之外拥有其他所有 Text节点的方法。 注释的实际内容可以通过 nodeValue 或 data 获得 document.createComment() 可以创建注释节点 1.4.1.6 CDATASection 类型 XML 中特有的 CDATA 区块 可以用 createCDataSection() 创建并传入节点内容创建\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"第十四章 14.1.5-14.1.9(续接前面本章完)\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"14.1.5 Comment 类型\",\"slug\":\"_14-1-5-comment-类型\",\"link\":\"#_14-1-5-comment-类型\",\"children\":[]},{\"level\":2,\"title\":\"1.4.1.6 CDATASection 类型\",\"slug\":\"_1-4-1-6-cdatasection-类型\",\"link\":\"#_1-4-1-6-cdatasection-类型\",\"children\":[]},{\"level\":2,\"title\":\"14.1.7 DocumentType 类型\",\"slug\":\"_14-1-7-documenttype-类型\",\"link\":\"#_14-1-7-documenttype-类型\",\"children\":[]},{\"level\":2,\"title\":\"14.1.8 DocumentFragment 类型\",\"slug\":\"_14-1-8-documentfragment-类型\",\"link\":\"#_14-1-8-documentfragment-类型\",\"children\":[]},{\"level\":2,\"title\":\"14.1.9 Attr 类型\",\"slug\":\"_14-1-9-attr-类型\",\"link\":\"#_14-1-9-attr-类型\",\"children\":[]}],\"readingTime\":{\"minutes\":1.41,\"words\":423},\"filePathRelative\":\"posts/JavaScipt基础/红宝书/第十四章 14.1.5-14.1.9(续接前面本章完）.md\",\"excerpt\":\"<h1> 第十四章 14.1.5-14.1.9(续接前面本章完)</h1>\\n<h2> 14.1.5 Comment 类型</h2>\\n<p>注释类型节点，一般不主动创建。和文本类型一样继承自 CharacterData 基类，除了 splitText() 之外拥有其他所有 Text节点的方法。</p>\\n<p>注释的实际内容可以通过 nodeValue 或 data 获得</p>\\n<p>document.createComment() 可以创建注释节点</p>\\n<h2> 1.4.1.6 CDATASection 类型</h2>\\n<p>XML 中特有的 CDATA 区块</p>\\n<p>可以用 createCDataSection() 创建并传入节点内容创建</p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
