export const themeData = JSON.parse("{\"encrypt\":{\"config\":{\"/demo/encrypt.html\":[\"$2a$10$ahejMPSRCbuhqAmtx0/zVuX/xX4ji0ujXVK7I/170qR1yjM3hvESm\"],\"/zh/demo/encrypt.html\":[\"$2a$10$/7jvefHFjq0Jugeun9.3aO7WgMTPk56ybuSwvsKq2o.jim46lj5UW\"]}},\"blog\":{\"medias\":{\"GitHub\":\"https://github.com\"}},\"locales\":{\"/\":{\"lang\":\"zh-CN\",\"navbarLocales\":{\"langName\":\"简体中文\",\"selectLangAriaLabel\":\"选择语言\"},\"metaLocales\":{\"author\":\"作者\",\"date\":\"写作日期\",\"origin\":\"原创\",\"views\":\"访问量\",\"category\":\"分类\",\"tag\":\"标签\",\"readingTime\":\"阅读时间\",\"words\":\"字数\",\"toc\":\"此页内容\",\"prev\":\"上一页\",\"next\":\"下一页\",\"lastUpdated\":\"上次编辑于\",\"contributors\":\"贡献者\",\"editLink\":\"Edit this page on GitHub\"},\"blogLocales\":{\"article\":\"文章\",\"articleList\":\"文章列表\",\"category\":\"分类\",\"tag\":\"标签\",\"timeline\":\"时间轴\",\"timelineTitle\":\"昨日不在\",\"all\":\"全部\",\"intro\":\"个人介绍\",\"star\":\"收藏\"},\"paginationLocales\":{\"prev\":\"上一页\",\"next\":\"下一页\",\"navigate\":\"跳转到\",\"action\":\"前往\",\"errorText\":\"请输入 1 到 $page 之前的页码！\"},\"outlookLocales\":{\"themeColor\":\"主题色\",\"darkmode\":\"外观\",\"fullscreen\":\"全屏\"},\"encryptLocales\":{\"iconLabel\":\"文章已加密\",\"placeholder\":\"输入密码\",\"remember\":\"记住密码\",\"errorHint\":\"请输入正确的密码\"},\"routeLocales\":{\"skipToContent\":\"跳至主要內容\",\"notFoundTitle\":\"页面不存在\",\"notFoundMsg\":[\"这里什么也没有\",\"我们是怎么来到这儿的？\",\"这 是 四 零 四 !\",\"看起来你访问了一个失效的链接\"],\"back\":\"返回上一页\",\"home\":\"带我回家\",\"openInNewWindow\":\"Open in new window\"},\"author\":{\"name\":\"饮东\",\"url\":\"http://www.reonce.top/\"},\"logo\":\"/logo.svg\",\"repo\":\"vuepress-theme-hope/vuepress-theme-hope\",\"docsDir\":\"docs\",\"navbar\":[{\"text\":\"主页\",\"icon\":\"discover\",\"link\":\"/\"},{\"text\":\"分类\",\"icon\":\"note\",\"prefix\":\"/posts/\",\"link\":\"/posts/\",\"children\":[{\"text\":\"感悟\",\"icon\":\"edit\",\"prefix\":\"感悟\",\"children\":[]},{\"text\":\"苹果\",\"icon\":\"edit\",\"prefix\":\"apple/\",\"children\":[{\"text\":\"苹果1\",\"icon\":\"edit\",\"link\":\"1\"},{\"text\":\"苹果2\",\"icon\":\"edit\",\"link\":\"2\"},\"3\",\"4\"]},{\"text\":\"香蕉\",\"icon\":\"edit\",\"prefix\":\"banana/\",\"children\":[{\"text\":\"香蕉 1\",\"icon\":\"edit\",\"link\":\"1\"},{\"text\":\"香蕉 2\",\"icon\":\"edit\",\"link\":\"2\"},\"3\",\"4\"]}]},{\"text\":\"归档\",\"icon\":\"note\",\"prefix\":\"/posts/\",\"link\":\"/posts/\"},{\"text\":\"关于\",\"icon\":\"edit\",\"link\":\"/about/关于\"}],\"sidebar\":{\"/zh/\":[\"\",{\"text\":\"如何使用\",\"icon\":\"creative\",\"prefix\":\"demo/\",\"link\":\"demo/\",\"children\":\"structure\"},{\"text\":\"文章\",\"icon\":\"note\",\"prefix\":\"posts/\",\"children\":\"structure\"},\"intro\",\"slides\"]},\"footer\":\"Default footer\",\"displayFooter\":true,\"blog\":{\"description\":\"A FrontEnd programmer\",\"intro\":\"/intro.html\"}}}}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateThemeData) {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ themeData }) => {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  })
}
