export const data = JSON.parse("{\"key\":\"v-7f6a75ba\",\"path\":\"/zh/posts/JavaScipt%E5%9F%BA%E7%A1%80/%E7%BA%A2%E5%AE%9D%E4%B9%A6/14.1.4%20Text%E7%B1%BB%E5%9E%8B.html\",\"title\":\"14.1.4 Text类型\",\"lang\":\"zh-CN\",\"frontmatter\":{\"description\":\"14.1.4 Text类型 概念 Text 节点是由 Text 类型表示，也就是标签之间的文本字符 暴露了几个方法： appendData(text) deleteData(offset, count) 在 offset 开始删除 count个字符 insertData(offset, text) 在 offset 位置插入文本 replaceData(offset, count, text) 在 用 text 替换从 offset 开始的 count 个字符 splitText(offset) 在 offset 位置将文本拆分成两个文本节点 subStringData(offset, count) 提取从位置 offset 到 offset+count 的文本\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.github.io/zh/posts/JavaScipt%E5%9F%BA%E7%A1%80/%E7%BA%A2%E5%AE%9D%E4%B9%A6/14.1.4%20Text%E7%B1%BB%E5%9E%8B.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"饮东的博客\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"14.1.4 Text类型\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"14.1.4 Text类型 概念 Text 节点是由 Text 类型表示，也就是标签之间的文本字符 暴露了几个方法： appendData(text) deleteData(offset, count) 在 offset 开始删除 count个字符 insertData(offset, text) 在 offset 位置插入文本 replaceData(offset, count, text) 在 用 text 替换从 offset 开始的 count 个字符 splitText(offset) 在 offset 位置将文本拆分成两个文本节点 subStringData(offset, count) 提取从位置 offset 到 offset+count 的文本\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"14.1.4 Text类型\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"概念\",\"slug\":\"概念\",\"link\":\"#概念\",\"children\":[]},{\"level\":2,\"title\":\"创建文本节点\",\"slug\":\"创建文本节点\",\"link\":\"#创建文本节点\",\"children\":[]},{\"level\":2,\"title\":\"规范化文本节点\",\"slug\":\"规范化文本节点\",\"link\":\"#规范化文本节点\",\"children\":[]},{\"level\":2,\"title\":\"拆分文本节点\",\"slug\":\"拆分文本节点\",\"link\":\"#拆分文本节点\",\"children\":[]}],\"readingTime\":{\"minutes\":0.91,\"words\":273},\"filePathRelative\":\"zh/posts/JavaScipt基础/红宝书/14.1.4 Text类型.md\",\"excerpt\":\"<h1> 14.1.4 Text类型</h1>\\n<h2> 概念</h2>\\n<p>Text 节点是由 Text 类型表示，也就是标签之间的文本字符</p>\\n<p>暴露了几个方法：</p>\\n<ul>\\n<li>appendData(text)</li>\\n<li>deleteData(offset, count) 在 offset 开始删除 count个字符</li>\\n<li>insertData(offset, text)  在 offset 位置插入文本</li>\\n<li>replaceData(offset, count, text) 在 用 text 替换从 offset 开始的 count 个字符</li>\\n<li>splitText(offset) 在 offset 位置将文本拆分成两个文本节点</li>\\n<li>subStringData(offset, count) 提取从位置 offset 到 offset+count  的文本</li>\\n</ul>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
